//
//  LSPersistenceNotificationName.h
//  LSAPM
//
//  Created by Lumia_Saki on 2017/5/19.
//  Copyright © 2017年 tianren.zhu. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const LS_PERSISTENCE_FINISH_NOTIFICATION_IDENTIFIER;
FOUNDATION_EXPORT NSString *const LS_REMOVE_PERSISTENCE_FILES_NOTIFICATION_IDENTIFIER;
FOUNDATION_EXPORT NSString *const LS_REQUEST_PERSISTENCE_FILES_NOTIFICATION_IDENTIFIER;
FOUNDATION_EXPORT NSString *const LS_PERSISTENCE_FILES_RESPONSE_NOTIFICATION_IDENTIFIER;
